language: go

sudo: required

services:
  - docker

go:
  - 1.5

before_install:
  - docker build -t "rprakashg/go-o365api-explorer" .

install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "rprakashg/go-o365api-explorer"
